# Generated by Django 3.1.5 on 2022-04-10 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_author'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
