# Generated by Django 3.1.5 on 2022-04-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_auto_20220410_2255'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
